name: Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
      - name: npm install
        env:
          CI: true
        run: |
          cd mail-back
          npm ci
      - name: deploy
        run: |
          zip -j deploy.zip ./mail-back/utils/*
          aws lambda update-function-code --function-name=automate-send-emails --zip-file fileb://deploy.zip